{
    "contract": {
        "name": "JKEdwards_Employment_Contract",
        "version": 1.0,
        "description": "Employment contract for Josef Kurk Edwards integrating GitHub OAuth for automation.",
        "wallets": {
            "bitcoin_wallet": "35eNZo1A2RTWKkiFVCjxJeYdhUCVBSVL4d",
            "cosmos_wallet": "cosmos1erfvxk96wdjcure56lx5awqulhy3fk3vnwg0rd"
        },
        "github_token": "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"
    },
    "employee_details": {
        "name": "Josef Kurk Edwards",
        "title": "Principal Architect",
        "address": "6389 W Appomattox Ln, Homosassa, FL 34448",
        "dob": "June 11, 1995"
    },
    "compensation": {
        "base_salary": 300000,
        "token_compensation": {
            "amount": 50000,
            "currency": "ATOM",
            "vesting": {
                "total_months": 48,
                "cliff_months": 12
            }
        }
    },
    "benefits": {
        "healthcare": "Comprehensive medical, dental, and vision"
    },
    "termination_clauses": {
        "voluntary": "30-day notice required"
    }
}

{
    "contract": {
        "name": "JKEdwards_Employment_Contract",
        "version": 1.0,
        "description": "Employment contract for Josef Kurk Edwards integrating GitHub OAuth for automation.",
        "wallets": {
            "bitcoin_wallet": "35eNZo1A2RTWKkiFVCjxJeYdhUCVBSVL4d",
            "cosmos_wallet": "cosmos1erfvxk96wdjcure56lx5awqulhy3fk3vnwg0rd"
        },
        "github_token": "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"
    },
    "employee_details": {
        "name": "Josef Kurk Edwards",
        "title": "Principal Architect",
        "address": "6389 W Appomattox Ln, Homosassa, FL 34448",
        "dob": "June 11, 1995"
    },
    "compensation": {
        "base_salary": 300000,
        "token_compensation": {
            "amount": 50000,
            "currency": "ATOM",
            "vesting": {
                "total_months": 48,
                "cliff_months": 12
            }
        }
    },
    "benefits": {
        "healthcare": "Comprehensive medical, dental, and vision"
    },
    "termination_clauses": {
        "voluntary": "30-day notice required"
    }
}

name: Bearycool Employment Contract Automation

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of this workflow

env:
  CONTRACT_NAME: "JKEdwards_Employment_Contract"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WALLET_ADDRESS: "cosmos1erfvxk96wdjcure56lx5awqulhy3fk3vnwg0rd"

jobs:
  deploy-contract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Compile Smart Contract
        run: |
          cargo build --release --target wasm32-unknown-unknown
          mv target/wasm32-unknown-unknown/release/contract.wasm ./contract.wasm

      - name: Deploy Smart Contract
        env:
          COSMOS_PRIVATE_KEY: ${{ secrets.COSMOS_PRIVATE_KEY }}
        run: |
          gaiad tx wasm store contract.wasm --from $WALLET_ADDRESS --gas auto --fees 2000uatom --chain-id cosmoshub-4 --node https://rpc.cosmoshub-4.io --yes
          CODE_ID=$(gaiad query wasm list-code --output json | jq -r '.code_infos[-1].code_id')
          echo "CODE_ID=${CODE_ID}" >> $GITHUB_ENV

      - name: Instantiate Contract
        run: |
          gaiad tx wasm instantiate $CODE_ID '{
            "github_token": "${{ secrets.GITHUB_TOKEN }}",
            "employee_name": "Josef Kurk Edwards",
            "base_salary": 300000,
            "ppu_equity": 10,
            "vesting_months": 48,
            "performance_bonus": 20,
            "healthcare": "Comprehensive medical, dental, and vision",
            "pto_policy": "Unlimited PTO policy and 18 days annually",
            "retirement_plan": "401(k) with 5% company match",
            "professional_stipend": 10000,
            "bitcoin_wallet": "35eNZo1A2RTWKkiFVCjxJeYdhUCVBSVL4d",
            "cosmos_wallet": "cosmos1erfvxk96wdjcure56lx5awqulhy3fk3vnwg0rd"
          }' --from $WALLET_ADDRESS --chain-id cosmoshub-4 --node https://rpc.cosmoshub-4.io --yes

  automate-github:
    runs-on: ubuntu-latest

    steps:
      - name: Use GitHub Token
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user
